### ISSUE TITLE
[1.14.4] Chests do not move or sort items 

### ISSUE THREAD

**Issue by ManO1234148** [arboriginal/TidyingChest#9]
**Describe the bug**
When a tidyingchest system is set up in 1.14.4 items do not move from master-chest to endpoint-chest at all, and console gives no errors.

**To Reproduce**
Load up 1.14.4 server. Make any master-chest anywhere and any slave-chest with any item. Put an item in master-chest. The item will not be sorted and in fact just stay in the master chest and nothing will occur. Messages and signs still function correctly

**Expected behavior**

**Screenshots**
![2019-12-27_17 35 38](https://user-images.githubusercontent.com/29739282/71536689-57869300-28cf-11ea-8675-db3c43724f5d.png)
![2019-12-27_17 35 40](https://user-images.githubusercontent.com/29739282/71536692-5b1a1a00-28cf-11ea-9f43-7ed2f4432748.png)
![2019-12-27_17 35 42](https://user-images.githubusercontent.com/29739282/71536693-5e150a80-28cf-11ea-97ec-1c91dddb30e9.png)

**Environment**
 - Java: [Java 8]
 - Spigot / Paper version: Spigot [94-af569-6ddeb98] [MC 1.14.4]
 - Plugin version: TidyingChest [0.9]
 - Plugin configuration (use [Gist](http://gist.github.com), [pastebin](https://pastebin.com) or similar)

**Additional context**
Trying to set up small server for friends. Plugin list is as follows: 
- AdvancedEnchantmnents
- Fast Async World Edit
- EpicHoppers
- EssentialsX
- LuckPerms 
- PlugMan 
- SmoothTimber
- TidyingChest
- TrollV4
- Vault

Replicated this on an empty server as well with just your plugin and luckperms running

By submitting this issue, you confirm having read, understand and accepted its guideline.
You also confirm having a functional brain activated during the writing of this issue.

**YES**

**Comment by ManO1234148** [comment]
IT only seems to occur when double chests are involved

**Comment by ManO1234148** [comment]
specifically with double chests as the deposit chestt

**Comment by arboriginal** [comment]
Fixed in release 1.0.
